image: obarun/base:latest

before_script:
  - pacman -Syu --noconfirm
  - pacman -S base-devel meson git lowdown --noconfirm

stages:
  - build
  - release
  - request

request:
  stage: request
  script:
  - ./build_toolchain.sh "commit"
  - meson setup build
  - meson compile -C build
  - DESTDIR=gitlab-ci meson install -C build


  only:
  - merge_requests

build:
  stage: build
  script:
  - ./build_toolchain.sh "commit"
  - meson setup build
  - meson compile -C build
  - meson test -C build
  - DESTDIR=gitlab-ci meson install -C build

  only:
    refs:
      - master

release:
  stage: release
  script:
  - ./build_toolchain.sh
  - meson setup build -D with-doc=true
  - meson compile -C build
  - meson test -C build
  - DESTDIR=gitlab-ci meson install -C build

  only:
      refs:
        - tags

