image: obarun/base:latest

before_script:
  - pacman -Syu --noconfirm
  - pacman -S autoconf automake binutils bison file flex gcc gettext grep groff libtool m4 make patch pkgconf texinfo which --noconfirm
  - pacman -S skalibs execline oblibs scdoc --noconfirm
  
build:
  stage: build
  script:
  - ./configure --bindir=/usr/bin 
  - make
  - make install-html DESTDIR=gitlab-ci
  - make man
  - make install DESTDIR=gitlab-ci
  - make install-man DESTDIR=gitlab-ci
  
  retry:
    max: 2

  only:
    - tags
    
