#
# This file has been generated by tools/gen-deps.sh
#

src/66-tools/66-clock.o src/66-tools/66-clock.lo: src/66-tools/66-clock.c
src/66-tools/66-getenv.o src/66-tools/66-getenv.lo: src/66-tools/66-getenv.c
src/66-tools/66-gnwenv.o src/66-tools/66-gnwenv.lo: src/66-tools/66-gnwenv.c
src/66-tools/66-ns.o src/66-tools/66-ns.lo: src/66-tools/66-ns.c src/include/66-tools/config.h
src/66-tools/66-olexec.o src/66-tools/66-olexec.lo: src/66-tools/66-olexec.c
src/66-tools/66-which.o src/66-tools/66-which.lo: src/66-tools/66-which.c
src/66-tools/66-writenv.o src/66-tools/66-writenv.lo: src/66-tools/66-writenv.c
src/66-tools/66-yeller.o src/66-tools/66-yeller.lo: src/66-tools/66-yeller.c
src/66-tools/execl-cmdline.o src/66-tools/execl-cmdline.lo: src/66-tools/execl-cmdline.c
src/66-tools/execl-subuidgid.o src/66-tools/execl-subuidgid.lo: src/66-tools/execl-subuidgid.c
src/66-tools/execl-toc.o src/66-tools/execl-toc.lo: src/66-tools/execl-toc.c
66-clock: EXTRA_LIBS := -loblibs -lskarnet
66-clock: src/66-tools/66-clock.o 
66-getenv: EXTRA_LIBS := -loblibs -lskarnet
66-getenv: src/66-tools/66-getenv.o 
66-gnwenv: EXTRA_LIBS := -loblibs -lskarnet
66-gnwenv: src/66-tools/66-gnwenv.o 
66-ns: EXTRA_LIBS := -loblibs -lskarnet
66-ns: src/66-tools/66-ns.o 
66-olexec: EXTRA_LIBS := -loblibs -lskarnet
66-olexec: src/66-tools/66-olexec.o 
66-which: EXTRA_LIBS := -loblibs -lskarnet
66-which: src/66-tools/66-which.o 
66-writenv: EXTRA_LIBS := -loblibs -lskarnet
66-writenv: src/66-tools/66-writenv.o
66-yeller: EXTRA_LIBS := -loblibs -lskarnet
66-yeller: src/66-tools/66-yeller.o 
execl-cmdline: EXTRA_LIBS := -loblibs -lexecline -lskarnet
execl-cmdline: src/66-tools/execl-cmdline.o
execl-subuidgid: EXTRA_LIBS := -loblibs -lexecline -lskarnet
execl-subuidgid: src/66-tools/execl-subuidgid.o ${LIBEXECLINE}
execl-toc: EXTRA_LIBS := -loblibs -lexecline -lskarnet
execl-toc: src/66-tools/execl-toc.o
