#
# This file has been generated by tools/gen-deps.sh
#

src/66-tools/66-envfile.o src/66-tools/66-envfile.lo: src/66-tools/66-envfile.c
src/66-tools/66-getenv.o src/66-tools/66-getenv.lo: src/66-tools/66-getenv.c
src/66-tools/66-gnwenv.o src/66-tools/66-gnwenv.lo: src/66-tools/66-gnwenv.c
src/66-tools/66-which.o src/66-tools/66-which.lo: src/66-tools/66-which.c
src/66-tools/66-writenv.o src/66-tools/66-writenv.lo: src/66-tools/66-writenv.c
src/66-tools/execl-cmdline.o src/66-tools/execl-cmdline.lo: src/66-tools/execl-cmdline.c
src/66-tools/execl-envfile.o src/66-tools/execl-envfile.lo: src/66-tools/execl-envfile.c
src/66-tools/execl-subuidgid.o src/66-tools/execl-subuidgid.lo: src/66-tools/execl-subuidgid.c

66-envfile: EXTRA_LIBS :=
66-envfile: src/66-tools/66-envfile.o -lskarnet
66-getenv: EXTRA_LIBS :=
66-getenv: src/66-tools/66-getenv.o -loblibs -lskarnet 
66-gnwenv: EXTRA_LIBS :=
66-gnwenv: src/66-tools/66-gnwenv.o -loblibs -lskarnet 
66-which: EXTRA_LIBS :=
66-which: src/66-tools/66-which.o -lskarnet -loblibs
66-writenv: EXTRA_LIBS :=
66-writenv: src/66-tools/66-writenv.o -lskarnet
execl-cmdline: EXTRA_LIBS :=
execl-cmdline: src/66-tools/execl-cmdline.o -lexecline -loblibs -lskarnet
execl-envfile: EXTRA_LIBS :=
execl-envfile: src/66-tools/execl-envfile.o ${LIBEXECLINE} -loblibs -lexecline -lskarnet 
execl-subuidgid: EXTRA_LIBS :=
execl-subuidgid: src/66-tools/execl-subuidgid.o -loblibs -lexecline -lskarnet ${LIBEXECLINE}
